

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pokemondb
        username: root
        password: Cyt1694458081
        driver-class-name: com.mysql.jdbc.Driver
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.pkm.pkmdb.object

